name: session_wrapper
description: "A Flutter widget that wraps your app to track user inactivity and trigger session timeout logic using a customizable controller."
version: 0.0.1
homepage: https://github.com/Dipak677/session_wrapper

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter: